/* PharmaDrug Glossary — simplified student definitions aligned with
   Lippincott Illustrated Reviews: Pharmacology (conceptual teaching terms).
   Educational summaries only; not a substitute for the textbook. */
window.PHARMADRUG_GLOSSARY = [
  { term: "Agonist", definition: "A drug that binds a receptor and activates it, producing a biological response similar to the endogenous ligand.", chapterHint: "Receptor pharmacology" },
  { term: "Antagonist", definition: "A drug that binds a receptor but does not activate it; it blocks or reduces the effect of agonists.", chapterHint: "Receptor pharmacology" },
  { term: "Partial agonist", definition: "A drug that activates a receptor but produces a smaller maximal response than a full agonist, even when all receptors are occupied.", chapterHint: "Receptor pharmacology" },
  { term: "Inverse agonist", definition: "A ligand that stabilizes the inactive form of a receptor and reduces constitutive (baseline) receptor activity.", chapterHint: "Receptor pharmacology" },
  { term: "Affinity", definition: "How tightly a drug binds its receptor; higher affinity means a lower concentration is needed for binding.", chapterHint: "Receptor pharmacology" },
  { term: "Efficacy", definition: "The ability of a drug–receptor complex to produce a maximal functional response.", chapterHint: "Receptor pharmacology" },
  { term: "Potency", definition: "The amount of drug needed to produce a given effect; a more potent drug reaches the effect at a lower dose.", chapterHint: "Dose–response" },
  { term: "Therapeutic index", definition: "A measure of drug safety relating the dose that causes toxicity to the dose that causes the desired effect; a wider index generally means a safer margin.", chapterHint: "Dose–response / safety" },
  { term: "ED50", definition: "The dose of a drug that produces 50% of the maximal effect in a graded response, or the dose effective in 50% of a population.", chapterHint: "Dose–response" },
  { term: "TD50", definition: "The dose that produces a toxic effect in 50% of the population; used with ED50 when discussing safety margins.", chapterHint: "Dose–response / safety" },
  { term: "Pharmacokinetics (PK)", definition: "What the body does to the drug: absorption, distribution, metabolism, and excretion (ADME).", chapterHint: "Pharmacokinetics" },
  { term: "Pharmacodynamics (PD)", definition: "What the drug does to the body: receptor actions, biochemical and physiological effects, and dose–response relationships.", chapterHint: "Pharmacodynamics" },
  { term: "Absorption", definition: "Movement of drug from the site of administration into the systemic circulation.", chapterHint: "ADME" },
  { term: "Bioavailability", definition: "The fraction of an administered dose that reaches systemic circulation in active form; IV bioavailability is 100%.", chapterHint: "ADME" },
  { term: "First-pass metabolism", definition: "Metabolism of a drug in the gut wall and/or liver before it reaches systemic circulation, reducing oral bioavailability.", chapterHint: "ADME" },
  { term: "Distribution", definition: "Reversible movement of drug from blood into tissues and body compartments.", chapterHint: "ADME" },
  { term: "Volume of distribution (Vd)", definition: "A theoretical volume relating the amount of drug in the body to plasma concentration; high Vd suggests extensive tissue distribution.", chapterHint: "ADME" },
  { term: "Metabolism", definition: "Chemical alteration of a drug, mainly in the liver, often to more polar metabolites for excretion.", chapterHint: "ADME" },
  { term: "Phase I reaction", definition: "Functionalization reactions (oxidation, reduction, hydrolysis), frequently mediated by cytochrome P450 enzymes.", chapterHint: "Biotransformation" },
  { term: "Phase II reaction", definition: "Conjugation reactions (e.g., glucuronidation, sulfation, acetylation) that increase water solubility for elimination.", chapterHint: "Biotransformation" },
  { term: "Cytochrome P450 (CYP)", definition: "A family of hepatic enzymes that oxidize many drugs; major source of metabolic drug interactions.", chapterHint: "Biotransformation" },
  { term: "Prodrug", definition: "An inactive compound converted in the body to an active drug, often via metabolism.", chapterHint: "Biotransformation" },
  { term: "Excretion", definition: "Removal of drug or metabolites from the body, commonly via kidney (urine) or liver (bile).", chapterHint: "ADME" },
  { term: "Half-life (t½)", definition: "Time required for the plasma concentration of a drug to fall by one-half; guides dosing interval.", chapterHint: "PK parameters" },
  { term: "Steady state", definition: "The condition when drug input equals elimination so average plasma levels become stable, typically after about 4–5 half-lives with regular dosing.", chapterHint: "PK parameters" },
  { term: "Clearance", definition: "The volume of plasma cleared of drug per unit time; a primary determinant of maintenance dose rate.", chapterHint: "PK parameters" },
  { term: "Loading dose", definition: "A larger initial dose used to reach target concentration rapidly, especially for drugs with long half-lives.", chapterHint: "Dosing" },
  { term: "Maintenance dose", definition: "The dose rate needed to maintain a steady-state concentration by replacing drug lost through clearance.", chapterHint: "Dosing" },
  { term: "Therapeutic window", definition: "The range of concentrations between the minimum effective level and the minimum toxic level.", chapterHint: "Safety" },
  { term: "Tolerance", definition: "Reduced response to a drug after repeated use, so a higher dose may be needed for the same effect.", chapterHint: "Drug response" },
  { term: "Dependence", definition: "A state in which continued drug exposure is needed to avoid withdrawal symptoms (physical) or craving (psychological).", chapterHint: "CNS / opioids" },
  { term: "Withdrawal", definition: "A characteristic set of symptoms that appear when a drug is reduced or stopped after dependence has developed.", chapterHint: "CNS / opioids" },
  { term: "Sympathetic nervous system", definition: "Autonomic division associated with “fight or flight” responses (e.g., increased heart rate, bronchodilation, pupil dilation).", chapterHint: "Autonomic pharmacology" },
  { term: "Parasympathetic nervous system", definition: "Autonomic division associated with “rest and digest” functions (e.g., slowing heart rate, increasing secretions and GI motility).", chapterHint: "Autonomic pharmacology" },
  { term: "Cholinergic", definition: "Related to acetylcholine; cholinergic drugs mimic or enhance acetylcholine actions at muscarinic or nicotinic receptors.", chapterHint: "Autonomic pharmacology" },
  { term: "Adrenergic", definition: "Related to norepinephrine/epinephrine; adrenergic drugs act on alpha or beta adrenoceptors.", chapterHint: "Autonomic pharmacology" },
  { term: "Muscarinic receptor", definition: "G protein–coupled acetylcholine receptor subtype found on parasympathetic effector organs (and some other sites).", chapterHint: "Autonomic pharmacology" },
  { term: "Nicotinic receptor", definition: "Ligand-gated ion channel receptor for acetylcholine at neuromuscular junctions and autonomic ganglia.", chapterHint: "Autonomic pharmacology" },
  { term: "Alpha-blocker", definition: "Drug that antagonizes alpha-adrenergic receptors, often used to lower vascular tone or relax smooth muscle in selected tissues.", chapterHint: "Adrenergic antagonists" },
  { term: "Beta-blocker", definition: "Drug that antagonizes beta-adrenergic receptors; effects include reduced heart rate and contractility (beta-1) and possible bronchoconstriction (beta-2 blockade).", chapterHint: "Adrenergic antagonists" },
  { term: "ACE inhibitor", definition: "Drug that blocks angiotensin-converting enzyme, reducing angiotensin II formation and lowering blood pressure; may cause cough via bradykinin.", chapterHint: "Cardiovascular" },
  { term: "ARB", definition: "Angiotensin receptor blocker; antagonizes AT1 receptors, lowering blood pressure without increasing bradykinin the way ACE inhibitors do.", chapterHint: "Cardiovascular" },
  { term: "Calcium channel blocker", definition: "Drug that inhibits L-type calcium channels in vascular smooth muscle and/or cardiac tissue, causing vasodilation and/or reduced cardiac conduction/contractility.", chapterHint: "Cardiovascular" },
  { term: "Diuretic", definition: "Drug that increases urine output by inhibiting renal sodium (and water) reabsorption at specific nephron sites.", chapterHint: "Renal / cardiovascular" },
  { term: "Loop diuretic", definition: "Diuretic acting on the thick ascending limb of the loop of Henle (e.g., NKCC2 inhibition), producing potent diuresis.", chapterHint: "Renal" },
  { term: "Thiazide diuretic", definition: "Diuretic acting mainly on the distal convoluted tubule (NCC inhibition); widely used in hypertension.", chapterHint: "Renal" },
  { term: "Inotrope", definition: "Agent that changes the force of muscle contraction; positive inotropes increase cardiac contractility.", chapterHint: "Cardiovascular" },
  { term: "Chronotrope", definition: "Agent that changes heart rate; positive chronotropes increase rate, negative chronotropes decrease rate.", chapterHint: "Cardiovascular" },
  { term: "Bactericidal", definition: "Antimicrobial action that kills bacteria (as opposed to only inhibiting growth).", chapterHint: "Antimicrobials" },
  { term: "Bacteriostatic", definition: "Antimicrobial action that inhibits bacterial growth and replication, relying on host defenses to clear infection.", chapterHint: "Antimicrobials" },
  { term: "Broad-spectrum", definition: "Activity against a wide range of bacterial types (e.g., many Gram-positive and Gram-negative organisms).", chapterHint: "Antimicrobials" },
  { term: "Resistance", definition: "Ability of a microorganism to withstand drug action through mechanisms such as enzymatic inactivation, altered targets, or efflux pumps.", chapterHint: "Antimicrobials" },
  { term: "Beta-lactam", definition: "Antibiotic class containing a beta-lactam ring (penicillins, cephalosporins, carbapenems, monobactams) that inhibits bacterial cell wall synthesis.", chapterHint: "Antimicrobials" },
  { term: "Beta-lactamase", definition: "Bacterial enzyme that hydrolyzes the beta-lactam ring, inactivating many beta-lactam antibiotics.", chapterHint: "Antimicrobials" },
  { term: "Gram-positive", definition: "Bacteria with a thick peptidoglycan cell wall that stain purple with Gram stain; often targeted by different antibiotic groups than Gram-negatives.", chapterHint: "Antimicrobials" },
  { term: "Gram-negative", definition: "Bacteria with an outer membrane and thinner peptidoglycan layer that stain pink with Gram stain; outer membrane affects antibiotic entry.", chapterHint: "Antimicrobials" },
  { term: "NSAID", definition: "Nonsteroidal anti-inflammatory drug; inhibits cyclooxygenase (COX) enzymes, reducing prostaglandin synthesis and thereby pain, fever, and inflammation.", chapterHint: "Autacoids / inflammation" },
  { term: "COX-1 / COX-2", definition: "Cyclooxygenase isoforms; COX-1 is more constitutive (including gastric protection), COX-2 is more inducible at inflammation sites.", chapterHint: "Autacoids / inflammation" },
  { term: "Corticosteroid", definition: "Glucocorticoid drug that broadly suppresses inflammation and immune responses via genomic and other mechanisms.", chapterHint: "Anti-inflammatory / endocrine" },
  { term: "Insulin", definition: "Hormone (and drug) that promotes glucose uptake and storage and inhibits glucose production; essential in type 1 diabetes therapy.", chapterHint: "Endocrine" },
  { term: "Hypoglycemia", definition: "Abnormally low blood glucose; an important adverse effect of insulin and some oral antidiabetic agents.", chapterHint: "Endocrine" },
  { term: "SSRI", definition: "Selective serotonin reuptake inhibitor; antidepressant class that increases synaptic serotonin by blocking its reuptake transporter.", chapterHint: "CNS / antidepressants" },
  { term: "Benzodiazepine", definition: "Drug that enhances GABA-A receptor activity, producing anxiolytic, sedative, muscle-relaxant, and anticonvulsant effects.", chapterHint: "CNS" },
  { term: "GABA", definition: "Gamma-aminobutyric acid, the major inhibitory neurotransmitter in the CNS.", chapterHint: "CNS" },
  { term: "Dopamine", definition: "CNS neurotransmitter involved in movement, reward, and hormone regulation; targeted by antiparkinsonian and antipsychotic drugs.", chapterHint: "CNS" },
  { term: "Acetylcholinesterase inhibitor", definition: "Drug that blocks breakdown of acetylcholine, increasing cholinergic transmission (used in myasthenia and some dementia treatments).", chapterHint: "Autonomic / CNS" },
  { term: "Warfarin", definition: "Oral anticoagulant that inhibits vitamin K–dependent clotting factor synthesis; monitored with INR and prone to many interactions.", chapterHint: "Hematology" },
  { term: "Heparin", definition: "Parenteral anticoagulant that potentiates antithrombin, accelerating inactivation of clotting factors such as thrombin and Xa.", chapterHint: "Hematology" },
  { term: "INR", definition: "International Normalized Ratio; standardized PT ratio used to monitor warfarin therapy.", chapterHint: "Hematology" },
  { term: "Statin", definition: "HMG-CoA reductase inhibitor that lowers cholesterol synthesis in the liver and is used primarily for dyslipidemia and cardiovascular risk reduction.", chapterHint: "Lipid pharmacology" },
  { term: "HMG-CoA reductase", definition: "Rate-limiting enzyme in hepatic cholesterol synthesis; inhibited by statin drugs.", chapterHint: "Lipid pharmacology" },
  { term: "Receptor downregulation", definition: "Decrease in receptor number or sensitivity after prolonged agonist exposure, contributing to tolerance.", chapterHint: "Receptor pharmacology" },
  { term: "Spare receptors", definition: "Situation where maximal response occurs without occupying all receptors, so EC50 can be lower than Kd.", chapterHint: "Receptor pharmacology" },
  { term: "Competitive antagonist", definition: "Antagonist that binds the same site as the agonist; surmountable by higher agonist concentration (parallel right shift of dose–response curve).", chapterHint: "Receptor pharmacology" },
  { term: "Noncompetitive antagonist", definition: "Antagonist that reduces maximal agonist effect, often by irreversible or allosteric mechanisms not fully overcome by more agonist.", chapterHint: "Receptor pharmacology" },
  { term: "Allosteric modulator", definition: "Ligand that binds a site different from the orthosteric site and changes receptor response to the primary ligand.", chapterHint: "Receptor pharmacology" },
  { term: "Idiosyncratic reaction", definition: "Uncommon drug response not predictable from the usual pharmacology, sometimes related to genetics or immune mechanisms.", chapterHint: "Adverse effects" },
  { term: "Teratogen", definition: "Agent that can cause fetal structural or functional abnormalities when exposure occurs during pregnancy.", chapterHint: "Special populations" },
  { term: "Pharmacogenomics", definition: "Study of how genetic variation alters drug response, metabolism, efficacy, or toxicity.", chapterHint: "Individual variation" }
];
