// Educational drug–drug interaction reference for PharmaDrug
// Summarized teaching points inspired by standard pharmacology education
// (e.g., Lippincott-style topics). NOT verbatim copyrighted text.
// Always verify with current clinical references before practice use.
window.interactionKnowledge = [
  // CYP induction / inhibition themes
  { id: 'sjw-cyp3a4', drugs: ['St. John\'s wort', 'CYP3A4 substrates'], classes: ['Herbal', 'CYP3A4 substrate'], mechanism: 'St. John\'s wort induces CYP3A4 and can lower levels of many CYP3A4 substrates.', effect: 'Reduced efficacy of coadministered CYP3A4 substrates (e.g., some immunosuppressants, oral contraceptives, HIV PIs).', significance: 'HIGH', management: 'Avoid combination when possible; monitor therapeutic effect.', category: 'Enzyme induction' },
  { id: 'cimetidine-cyp', drugs: ['Cimetidine', 'Warfarin'], classes: ['H2 antagonist', 'Anticoagulant'], mechanism: 'Cimetidine inhibits several CYP enzymes involved in warfarin metabolism.', effect: 'Increased anticoagulant effect / bleeding risk.', significance: 'HIGH', management: 'Prefer other H2 blockers or PPIs; monitor INR closely if combined.', category: 'Enzyme inhibition' },
  { id: 'rifampin-inducer', drugs: ['Rifampin', 'Warfarin'], classes: ['Rifamycin', 'Anticoagulant'], mechanism: 'Rifampin is a potent inducer of multiple CYP enzymes and transporters.', effect: 'Decreased warfarin effect; loss of anticoagulation.', significance: 'HIGH', management: 'Monitor INR; substantial dose adjustment may be required.', category: 'Enzyme induction' },
  { id: 'rifampin-ocp', drugs: ['Rifampin', 'Oral contraceptives'], classes: ['Rifamycin', 'Hormonal contraceptive'], mechanism: 'Induction of CYP3A4 increases hormone metabolism.', effect: 'Reduced contraceptive efficacy.', significance: 'HIGH', management: 'Use additional/non-hormonal contraception during and after therapy.', category: 'Enzyme induction' },
  { id: 'azole-cyp3a4', drugs: ['Ketoconazole', 'Simvastatin'], classes: ['Azole antifungal', 'Statin'], mechanism: 'Azoles inhibit CYP3A4; simvastatin is a sensitive CYP3A4 substrate.', effect: 'Increased statin levels → myopathy / rhabdomyolysis risk.', significance: 'HIGH', management: 'Avoid or use statin with less CYP3A4 dependence; monitor muscle symptoms.', category: 'Enzyme inhibition' },
  { id: 'clarithromycin-cyp', drugs: ['Clarithromycin', 'Simvastatin'], classes: ['Macrolide', 'Statin'], mechanism: 'Clarithromycin inhibits CYP3A4.', effect: 'Elevated statin exposure and toxicity risk.', significance: 'HIGH', management: 'Avoid combination; consider azithromycin (weaker interaction).', category: 'Enzyme inhibition' },
  { id: 'erythromycin-cyp', drugs: ['Erythromycin', 'Theophylline'], classes: ['Macrolide', 'Methylxanthine'], mechanism: 'Macrolide inhibition of theophylline metabolism.', effect: 'Theophylline toxicity (nausea, arrhythmia, seizures).', significance: 'HIGH', management: 'Monitor levels; dose reduce theophylline if needed.', category: 'Enzyme inhibition' },
  { id: 'cipro-theophylline', drugs: ['Ciprofloxacin', 'Theophylline'], classes: ['Fluoroquinolone', 'Methylxanthine'], mechanism: 'Ciprofloxacin inhibits CYP1A2-mediated theophylline clearance.', effect: 'Increased theophylline levels and toxicity risk.', significance: 'HIGH', management: 'Avoid or monitor levels closely.', category: 'Enzyme inhibition' },
  { id: 'fluoroquinolone-divalent', drugs: ['Ciprofloxacin', 'Antacids (Al/Mg)'], classes: ['Fluoroquinolone', 'Antacid'], mechanism: 'Chelation of fluoroquinolone by divalent/trivalent cations.', effect: 'Reduced antibiotic absorption and efficacy.', significance: 'MODERATE', management: 'Separate dosing by several hours.', category: 'Absorption' },
  { id: 'tetracycline-divalent', drugs: ['Doxycycline', 'Calcium / iron supplements'], classes: ['Tetracycline', 'Mineral supplement'], mechanism: 'Chelation in the gut reduces absorption.', effect: 'Subtherapeutic antibiotic levels.', significance: 'MODERATE', management: 'Separate administration times.', category: 'Absorption' },

  // Anticoagulants
  { id: 'warfarin-nsaid', drugs: ['Warfarin', 'Ibuprofen'], classes: ['Anticoagulant', 'NSAID'], mechanism: 'Additive bleeding risk; NSAIDs impair platelets and may affect warfarin binding/metabolism.', effect: 'Increased GI and overall bleeding risk.', significance: 'HIGH', management: 'Avoid chronic NSAID use; prefer acetaminophen if appropriate; monitor INR/bleeding.', category: 'Pharmacodynamic' },
  { id: 'warfarin-aspirin', drugs: ['Warfarin', 'Aspirin'], classes: ['Anticoagulant', 'Antiplatelet'], mechanism: 'Additive antihemostatic effects.', effect: 'Increased bleeding risk.', significance: 'HIGH', management: 'Use only when clearly indicated; monitor closely.', category: 'Pharmacodynamic' },
  { id: 'warfarin-amiodarone', drugs: ['Warfarin', 'Amiodarone'], classes: ['Anticoagulant', 'Class III antiarrhythmic'], mechanism: 'Amiodarone inhibits CYP2C9 and other pathways of warfarin metabolism.', effect: 'Potentiated anticoagulation.', significance: 'HIGH', management: 'Empiric warfarin dose reduction and frequent INR monitoring when starting amiodarone.', category: 'Enzyme inhibition' },
  { id: 'warfarin-metronidazole', drugs: ['Warfarin', 'Metronidazole'], classes: ['Anticoagulant', 'Antimicrobial'], mechanism: 'Inhibition of warfarin metabolism.', effect: 'Increased INR / bleeding.', significance: 'HIGH', management: 'Monitor INR; adjust warfarin dose.', category: 'Enzyme inhibition' },
  { id: 'warfarin-sulfamethoxazole', drugs: ['Warfarin', 'Trimethoprim-sulfamethoxazole'], classes: ['Anticoagulant', 'Sulfonamide antibiotic'], mechanism: 'CYP2C9 inhibition and other mechanisms.', effect: 'Markedly increased INR.', significance: 'HIGH', management: 'Prefer alternative antibiotic when possible; monitor INR closely.', category: 'Enzyme inhibition' },
  { id: 'doac-pgp', drugs: ['Rivaroxaban', 'Rifampin'], classes: ['DOAC', 'Rifamycin'], mechanism: 'Induction of P-gp/CYP3A4 reduces DOAC exposure.', effect: 'Loss of anticoagulant effect.', significance: 'HIGH', management: 'Avoid combination per labeling.', category: 'Transporter / enzyme' },

  // Cardiovascular
  { id: 'acei-k-sparing', drugs: ['Lisinopril', 'Spironolactone'], classes: ['ACE inhibitor', 'Potassium-sparing diuretic'], mechanism: 'Both raise serum potassium.', effect: 'Hyperkalemia.', significance: 'HIGH', management: 'Monitor K+ and renal function; caution in CKD.', category: 'Pharmacodynamic' },
  { id: 'acei-nsaid', drugs: ['Enalapril', 'Ibuprofen'], classes: ['ACE inhibitor', 'NSAID'], mechanism: 'NSAIDs reduce renal prostaglandins; combined with ACEI may worsen renal function (especially with diuretics).', effect: 'Acute kidney injury risk (“triple whammy” with diuretic).', significance: 'HIGH', management: 'Avoid routine NSAIDs in at-risk patients; monitor creatinine.', category: 'Pharmacodynamic' },
  { id: 'verapamil-beta', drugs: ['Verapamil', 'Propranolol'], classes: ['Non-DHP CCB', 'Beta-blocker'], mechanism: 'Additive negative inotropy/chronotropy.', effect: 'Bradycardia, AV block, heart depression.', significance: 'HIGH', management: 'Combine only with caution and monitoring.', category: 'Pharmacodynamic' },
  { id: 'diltiazem-statin', drugs: ['Diltiazem', 'Simvastatin'], classes: ['Non-DHP CCB', 'Statin'], mechanism: 'CYP3A4 inhibition increases simvastatin exposure.', effect: 'Myopathy risk.', significance: 'HIGH', management: 'Limit simvastatin dose or switch statin.', category: 'Enzyme inhibition' },
  { id: 'amiodarone-digoxin', drugs: ['Amiodarone', 'Digoxin'], classes: ['Class III antiarrhythmic', 'Cardiac glycoside'], mechanism: 'P-gp inhibition and reduced digoxin clearance.', effect: 'Digoxin toxicity.', significance: 'HIGH', management: 'Reduce digoxin dose ~50% and monitor levels/symptoms.', category: 'Transporter / clearance' },
  { id: 'quinidine-digoxin', drugs: ['Quinidine', 'Digoxin'], classes: ['Class Ia antiarrhythmic', 'Cardiac glycoside'], mechanism: 'P-gp inhibition increases digoxin levels.', effect: 'Digoxin toxicity.', significance: 'HIGH', management: 'Dose-adjust digoxin; monitor.', category: 'Transporter' },
  { id: 'nitrate-pde5', drugs: ['Nitroglycerin', 'Sildenafil'], classes: ['Nitrate', 'PDE-5 inhibitor'], mechanism: 'Excessive cGMP-mediated vasodilation.', effect: 'Severe hypotension.', significance: 'HIGH', management: 'Absolute contraindication.', category: 'Pharmacodynamic' },
  { id: 'beta-blocker-insulin', drugs: ['Propranolol', 'Insulin'], classes: ['Beta-blocker', 'Antidiabetic'], mechanism: 'Nonselective beta-blockers may mask tachycardia of hypoglycemia and affect recovery.', effect: 'Masked hypoglycemia; prolonged hypoglycemia possible.', significance: 'MODERATE', management: 'Counsel patients; prefer cardioselective agents when suitable.', category: 'Pharmacodynamic' },

  // CNS / psych
  { id: 'maoi-ssri', drugs: ['Phenelzine', 'Fluoxetine'], classes: ['MAOI', 'SSRI'], mechanism: 'Excess serotonergic activity.', effect: 'Serotonin syndrome (potentially life-threatening).', significance: 'HIGH', management: 'Contraindicated; observe washout periods.', category: 'Pharmacodynamic' },
  { id: 'maoi-tyramine', drugs: ['Phenelzine', 'Tyramine-rich foods'], classes: ['MAOI', 'Dietary amine'], mechanism: 'Impaired tyramine metabolism → norepinephrine release.', effect: 'Hypertensive crisis.', significance: 'HIGH', management: 'Strict dietary restrictions while on MAOIs.', category: 'Food-drug' },
  { id: 'ssri-tramadol', drugs: ['Sertraline', 'Tramadol'], classes: ['SSRI', 'Opioid analgesic'], mechanism: 'Additive serotonergic effects; tramadol also inhibits serotonin reuptake.', effect: 'Serotonin syndrome risk; also seizure risk.', significance: 'HIGH', management: 'Avoid or use extreme caution.', category: 'Pharmacodynamic' },
  { id: 'ssri-nsaid', drugs: ['Sertraline', 'Ibuprofen'], classes: ['SSRI', 'NSAID'], mechanism: 'Impaired interplatelet signaling + NSAID gastric effects.', effect: 'Increased GI bleeding risk.', significance: 'MODERATE', management: 'Caution; gastroprotection if needed.', category: 'Pharmacodynamic' },
  { id: 'tca-maoi', drugs: ['Amitriptyline', 'Phenelzine'], classes: ['TCA', 'MAOI'], mechanism: 'Excess monoamines.', effect: 'Severe hypertension, serotonin toxicity, seizures.', significance: 'HIGH', management: 'Contraindicated without specialist protocols.', category: 'Pharmacodynamic' },
  { id: 'levodopa-maoi', drugs: ['Levodopa', 'Nonselective MAOI'], classes: ['Dopamine precursor', 'MAOI'], mechanism: 'Excess catecholamines.', effect: 'Hypertensive reactions.', significance: 'HIGH', management: 'Avoid nonselective MAOIs with levodopa.', category: 'Pharmacodynamic' },
  { id: 'benzo-opioid', drugs: ['Diazepam', 'Morphine'], classes: ['Benzodiazepine', 'Opioid'], mechanism: 'Additive CNS and respiratory depression.', effect: 'Sedation, respiratory failure, death risk.', significance: 'HIGH', management: 'Avoid combination when possible; use lowest doses.', category: 'Pharmacodynamic' },
  { id: 'alcohol-cns', drugs: ['Alcohol', 'Lorazepam'], classes: ['Ethanol', 'Benzodiazepine'], mechanism: 'Additive CNS depression.', effect: 'Profound sedation / respiratory depression.', significance: 'HIGH', management: 'Avoid concurrent use.', category: 'Pharmacodynamic' },

  // Antiepileptics
  { id: 'carbamazepine-inducer', drugs: ['Carbamazepine', 'Oral contraceptives'], classes: ['Antiepileptic', 'Hormonal contraceptive'], mechanism: 'CYP3A4 induction.', effect: 'Contraceptive failure risk.', significance: 'HIGH', management: 'Use higher-estrogen or non-hormonal methods as advised.', category: 'Enzyme induction' },
  { id: 'phenytoin-warfarin', drugs: ['Phenytoin', 'Warfarin'], classes: ['Antiepileptic', 'Anticoagulant'], mechanism: 'Complex induction/competition for metabolism and binding.', effect: 'Unpredictable INR changes.', significance: 'HIGH', management: 'Close INR monitoring with any phenytoin change.', category: 'Complex extra' },
  { id: 'valproate-lamotrigine', drugs: ['Valproate', 'Lamotrigine'], classes: ['Antiepileptic', 'Antiepileptic'], mechanism: 'Valproate inhibits lamotrigine metabolism.', effect: 'Increased lamotrigine levels → rash / SJS risk.', significance: 'HIGH', management: 'Use lower lamotrigine titration doses with valproate.', category: 'Enzyme inhibition' },
  { id: 'levetiracetam-low', drugs: ['Levetiracetam', 'Most drugs'], classes: ['Antiepileptic', 'General'], mechanism: 'Primarily renal elimination; minimal CYP involvement.', effect: 'Few pharmacokinetic interactions.', significance: 'LOW', management: 'Still monitor clinical response; favorable interaction profile.', category: 'Low interaction risk' },

  // GI
  { id: 'ppi-ketoconazole', drugs: ['Omeprazole', 'Ketoconazole'], classes: ['PPI', 'Azole antifungal'], mechanism: 'Raised gastric pH reduces ketoconazole absorption.', effect: 'Reduced antifungal efficacy.', significance: 'MODERATE', management: 'Avoid or use alternative antifungal/acid suppression strategy.', category: 'Absorption' },
  { id: 'sucralfate-ppi', drugs: ['Sucralfate', 'Omeprazole'], classes: ['Mucosal protectant', 'PPI'], mechanism: 'Sucralfate needs acidic pH for activation.', effect: 'Reduced sucralfate efficacy.', significance: 'MODERATE', management: 'Separate dosing; avoid simultaneous acid suppression when possible.', category: 'Absorption' },
  { id: 'cimetidine-propranolol', drugs: ['Cimetidine', 'Propranolol'], classes: ['H2 antagonist', 'Beta-blocker'], mechanism: 'Inhibition of propranolol metabolism.', effect: 'Increased beta-blockade.', significance: 'MODERATE', management: 'Monitor HR/BP; consider alternative H2 blocker.', category: 'Enzyme inhibition' },

  // Endocrine / other
  { id: 'sulfonylurea-fluoroquinolone', drugs: ['Glipizide', 'Levofloxacin'], classes: ['Sulfonylurea', 'Fluoroquinolone'], mechanism: 'Complex effects on glucose homeostasis.', effect: 'Hypoglycemia or dysglycemia.', significance: 'MODERATE', management: 'Monitor glucose when starting/stopping antibiotic.', category: 'Pharmacodynamic' },
  { id: 'allopurinol-azathioprine', drugs: ['Allopurinol', 'Azathioprine'], classes: ['Xanthine oxidase inhibitor', 'Immunosuppressant'], mechanism: 'Xanthine oxidase inhibition increases thiopurine exposure.', effect: 'Severe myelosuppression.', significance: 'HIGH', management: 'Major dose reduction of azathioprine/6-MP or avoid.', category: 'Metabolic pathway' },
  { id: 'allopurinol-theophylline', drugs: ['Allopurinol', 'Theophylline'], classes: ['Xanthine oxidase inhibitor', 'Methylxanthine'], mechanism: 'Reduced theophylline clearance.', effect: 'Theophylline toxicity risk.', significance: 'MODERATE', management: 'Monitor levels.', category: 'Clearance' },
  { id: 'methotrexate-nsaid', drugs: ['Methotrexate', 'Ibuprofen'], classes: ['Antimetabolite', 'NSAID'], mechanism: 'Reduced renal methotrexate clearance.', effect: 'Methotrexate toxicity.', significance: 'HIGH', management: 'Avoid NSAIDs around high-dose MTX; caution with chronic low-dose.', category: 'Clearance' },

  // Neuromuscular / anesthesia teaching points
  { id: 'nmb-cholinesterase', drugs: ['Rocuronium', 'Neostigmine'], classes: ['Nondepolarizing NMB', 'Cholinesterase inhibitor'], mechanism: 'Cholinesterase inhibitors increase ACh at NMJ.', effect: 'Reversal of nondepolarizing block (therapeutic interaction).', significance: 'MODERATE', management: 'Used intentionally for reversal; dosing per protocol.', category: 'Pharmacodynamic' },
  { id: 'nmb-aminoglycoside', drugs: ['Vecuronium', 'Gentamicin'], classes: ['Nondepolarizing NMB', 'Aminoglycoside'], mechanism: 'Aminoglycosides can enhance neuromuscular blockade.', effect: 'Prolonged paralysis.', significance: 'MODERATE', management: 'Monitor recovery; caution in perioperative period.', category: 'Pharmacodynamic' },

  // Opioids
  { id: 'codeine-cyp2d6', drugs: ['Codeine', 'Fluoxetine'], classes: ['Opioid prodrug', 'CYP2D6 inhibitor'], mechanism: 'CYP2D6 converts codeine to morphine; inhibitors reduce activation.', effect: 'Reduced analgesic effect.', significance: 'MODERATE', management: 'Consider alternative analgesic.', category: 'Enzyme inhibition' },
  { id: 'tramadol-maoi', drugs: ['Tramadol', 'Phenelzine'], classes: ['Opioid analgesic', 'MAOI'], mechanism: 'Serotonergic + monoamine effects.', effect: 'Serotonin syndrome / seizures.', significance: 'HIGH', management: 'Contraindicated.', category: 'Pharmacodynamic' },
  { id: 'methadone-cyp', drugs: ['Methadone', 'Rifampin'], classes: ['Opioid', 'Rifamycin'], mechanism: 'Induction of methadone metabolism.', effect: 'Withdrawal / loss of effect.', significance: 'HIGH', management: 'Avoid or closely monitor and retitrate.', category: 'Enzyme induction' },

  // Antibiotics / TB / HIV teaching points
  { id: 'linezolid-ssri', drugs: ['Linezolid', 'Sertraline'], classes: ['Oxazolidinone', 'SSRI'], mechanism: 'Linezolid has weak MAOI activity.', effect: 'Serotonin syndrome risk.', significance: 'HIGH', management: 'Avoid combination when possible; monitor if unavoidable.', category: 'Pharmacodynamic' },
  { id: 'pi-cyp3a4', drugs: ['Ritonavir', 'Midazolam'], classes: ['HIV protease inhibitor / booster', 'Benzodiazepine'], mechanism: 'Potent CYP3A4 inhibition.', effect: 'Profound sedation from midazolam.', significance: 'HIGH', management: 'Avoid oral midazolam with strong PIs.', category: 'Enzyme inhibition' },
  { id: 'nnrti-inducer', drugs: ['Efavirenz', 'Methadone'], classes: ['NNRTI', 'Opioid'], mechanism: 'Enzyme induction lowers methadone levels.', effect: 'Opioid withdrawal symptoms.', significance: 'HIGH', management: 'Monitor and adjust methadone.', category: 'Enzyme induction' },

  // Class-level teaching summaries
  { id: 'statin-grapefruit', drugs: ['Simvastatin', 'Grapefruit juice'], classes: ['Statin', 'Food'], mechanism: 'Grapefruit inhibits intestinal CYP3A4.', effect: 'Increased statin exposure.', significance: 'MODERATE', management: 'Avoid large amounts of grapefruit with CYP3A4-metabolized statins.', category: 'Food-drug' },
  { id: 'ssri-triptan', drugs: ['Paroxetine', 'Sumatriptan'], classes: ['SSRI', 'Triptan'], mechanism: 'Additive serotonergic tone.', effect: 'Serotonin syndrome (uncommon but important).', significance: 'MODERATE', management: 'Counsel on symptoms; caution with multiple serotonergic agents.', category: 'Pharmacodynamic' },
  { id: 'lithium-nsaid', drugs: ['Lithium', 'Ibuprofen'], classes: ['Mood stabilizer', 'NSAID'], mechanism: 'NSAIDs reduce renal lithium clearance.', effect: 'Lithium toxicity.', significance: 'HIGH', management: 'Avoid NSAIDs or monitor lithium levels closely.', category: 'Clearance' },
  { id: 'lithium-acei', drugs: ['Lithium', 'Lisinopril'], classes: ['Mood stabilizer', 'ACE inhibitor'], mechanism: 'Reduced lithium clearance.', effect: 'Lithium toxicity.', significance: 'HIGH', management: 'Monitor levels after ACEI initiation.', category: 'Clearance' },
  { id: 'digoxin-loop', drugs: ['Digoxin', 'Furosemide'], classes: ['Cardiac glycoside', 'Loop diuretic'], mechanism: 'Diuretic-induced hypokalemia sensitizes myocardium to digoxin.', effect: 'Increased digoxin toxicity risk.', significance: 'HIGH', management: 'Maintain K+ in normal range; monitor.', category: 'Electrolyte-mediated' },
  { id: 'spironolactone-k', drugs: ['Spironolactone', 'Potassium supplements'], classes: ['Aldosterone antagonist', 'Electrolyte'], mechanism: 'Additive potassium retention.', effect: 'Hyperkalemia.', significance: 'HIGH', management: 'Avoid routine K+ supplements; monitor serum K+.', category: 'Pharmacodynamic' },
  { id: 'clopidogrel-omeprazole', drugs: ['Clopidogrel', 'Omeprazole'], classes: ['P2Y12 inhibitor', 'PPI'], mechanism: 'Omeprazole inhibits CYP2C19 activation of clopidogrel.', effect: 'Possible reduced antiplatelet effect.', significance: 'MODERATE', management: 'Prefer PPIs with less CYP2C19 inhibition if gastroprotection needed.', category: 'Enzyme inhibition' },
  { id: 'sildenafil-alpha', drugs: ['Sildenafil', 'Doxazosin'], classes: ['PDE-5 inhibitor', 'Alpha-1 blocker'], mechanism: 'Additive vasodilation.', effect: 'Symptomatic hypotension.', significance: 'HIGH', management: 'Stabilize alpha-blocker therapy first; separate dosing; start low.', category: 'Pharmacodynamic' },
  { id: 'isoniazid-carbamazepine', drugs: ['Isoniazid', 'Carbamazepine'], classes: ['Antitubercular', 'Antiepileptic'], mechanism: 'Isoniazid inhibits carbamazepine metabolism.', effect: 'Carbamazepine toxicity.', significance: 'HIGH', management: 'Monitor levels and adverse effects.', category: 'Enzyme inhibition' },
  { id: 'phenobarbital-induction', drugs: ['Phenobarbital', 'Warfarin'], classes: ['Barbiturate / AED', 'Anticoagulant'], mechanism: 'Strong enzyme induction.', effect: 'Reduced warfarin effect.', significance: 'HIGH', management: 'Monitor INR with initiation or discontinuation.', category: 'Enzyme induction' }
];
